# Generated by Django 4.2.2 on 2023-06-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_title', models.CharField(max_length=400)),
                ('box_image', models.ImageField(upload_to='static/images')),
                ('box_adress', models.CharField(max_length=200)),
                ('box_pub_date', models.DateTimeField(verbose_name='date published')),
                ('box_price', models.CharField(max_length=50)),
            ],
        ),
    ]
