# Generated by Django 4.2.2 on 2023-06-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='box_image',
            field=models.ImageField(upload_to='static/app1_images'),
        ),
    ]
