# Generated by Django 4.2.2 on 2023-06-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_box_box_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='box_image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
