# Generated by Django 4.2.2 on 2023-07-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_box_box_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hotel_Main_Img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='box',
            name='box_image',
            field=models.ImageField(upload_to='app1/static/images'),
        ),
    ]
